name: 'hevo_dbt_project'
version: '1.0.0'

profile: 'hevo_snowflake'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  hevo_dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
